using System;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text;
using WildHare.Extensions;
using WildHare.Extensions.ForTemplating;
using WildHare.Web.SchemaModels;
using static System.Environment;

namespace WildHare.Web
{
	public static class CodeGenFromSql
    {
        // FOR SCHEMA DOCS SEE: https: //docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-schema-collections

        private static string sqlConnString;
        private static string modelNamespace;           
        private static string outputFolder;             
		private static readonly string start = "\t\t";  // Indentation
        private static readonly string end = NewLine;

        private static ILookup<string, ColumnsSchema> sqlTables;

		public static string Init(string outputFolderPath, string namespaceRoot, string dbConnString, bool overwrite = false)
        {
            if (outputFolderPath.IsNullOrEmpty())
                throw new ArgumentNullException($"{nameof(CodeGenFromSql)}.{nameof(Init)} projectRoot is null or empty.");

            if (dbConnString.IsNullOrEmpty())
                throw new ArgumentNullException($"{nameof(CodeGenFromSql)}.{nameof(Init)} dbConnString is null or empty.");

            outputFolder = outputFolderPath;
            sqlConnString = dbConnString;
            modelNamespace = namespaceRoot;

            // Get list of table from SQL database
            sqlTables = GetTablesFromSQL(exclude: "__MigrationHistory");

            // 1) Loop through the tables
            // ============================================================
            // a) Generates models for all tables in the database. 

            // foreach (var table in sqlTables)
            // {
            //     CreateModelFromSQLTable(table.Key);
            // }

            // 2) Pre-Generate a list of tables - Alternate approach
            // ============================================================
            // a) Create a string list of tables to use in this Init(). 
            // b) ie: generate a string using the modelsToCreate function below and paste it into this Init. 
            // c) This gives you the ability to remove tables that are not needed. 
            // d) Add a second parameter for the model name if you need something different from the simple naming pattern
            // e) Mark the 'overwrite' property as false if it has customizations that should not be overridden later.

            var modelsToCreate = string.Join("\r\n", sqlTables.Select(s => $"CreateModelFromSQLTable(\"{s.Key}\", overwrite: true);"));
            Debug.WriteLine(modelsToCreate + NewLine);

            // Run for the first time and place the string generated by the Debug.WriteLine inline here:

            CreateModelFromSQLTable("data.CommonNames", "CommonNames", overwrite: true);
            CreateModelFromSQLTable("data.USCities", "USCities", overwrite: true);
            CreateModelFromSQLTable("dbo.AnswerRules", overwrite: true);
            CreateModelFromSQLTable("dbo.AnswerRuleTypes", overwrite: true);
            CreateModelFromSQLTable("dbo.AppUsers", overwrite: true);
            CreateModelFromSQLTable("dbo.ComplexWords", overwrite: true);
            CreateModelFromSQLTable("dbo.MeaningProps", overwrite: true);
            CreateModelFromSQLTable("dbo.MeaningRules", overwrite: true);
            CreateModelFromSQLTable("dbo.MeaningRuleTypes", overwrite: true);
            CreateModelFromSQLTable("dbo.Patterns", overwrite: true);
            CreateModelFromSQLTable("dbo.SymbolRules", overwrite: true);
            CreateModelFromSQLTable("dbo.SymbolRuleTypes", overwrite: true);
            CreateModelFromSQLTable("dbo.TestCases", overwrite: true);
            CreateModelFromSQLTable("dbo.TestResults", overwrite: true);
            CreateModelFromSQLTable("dbo.TestRuns", overwrite: true);
            CreateModelFromSQLTable("dbo.TokenRules", overwrite: true);
            CreateModelFromSQLTable("dbo.TokenRuleTypes", overwrite: true);
            CreateModelFromSQLTable("dbo.UnknownTexts", overwrite: true);
            CreateModelFromSQLTable("dbo.WordProps", overwrite: true);
            CreateModelFromSQLTable("dbo.Words", overwrite: true);

            string result = $"{nameof(CodeGenFromSql)}.{nameof(Init)} code written to '{outputFolder}'. Overwrite: {overwrite}";
            Debug.WriteLine(result);

            return result;
        }

		private static ILookup<string, ColumnsSchema> GetTablesFromSQL(string exclude = "")
		{
            string[] excludeList = exclude.Split(',').Select(a => a.Trim()).ToArray();

            using (var conn = new SqlConnection(sqlConnString))
			{
				conn.Open();

                // If you leave the conn.GetSchema() empty, it will get a list of ALL SQL Server Schema Collections
                // like "Columns" below, or "Tables", "Indexes", "Procedures", etc.
                // For our purposes, "Columns" (and the model that I generated for it) is the most appropriate.
                // Example for stored procedures:
                // var procedureColumnSchemas = conn.GetSchema("Procedures");
                // var proceduresList = procedureColumnSchemas.ToList<ProceduresSchema>();

                DataTable tableColumnSchemas = conn.GetSchema("Columns"); 

                var tablesList = tableColumnSchemas.ToList<ColumnsSchema>()
                                .Where(w => !excludeList.Any(e => w.Table_Name == e))
                                .OrderBy(o => o.Ordinal_Position)
					            .ToLookup(g => $"{g.Table_Schema}.{g.Table_Name}");
                return tablesList;
			};
		}

		private static bool CreateModelFromSQLTable(string tableName, string modelName = null, bool overwrite = true)
		{
            modelName = modelName ?? tableName.RemoveStartEnd("dbo.", "s");

            string output =  
            $@"using System;
            using System.ComponentModel.DataAnnotations;
    
            // Generated from table: {tableName}

            namespace {modelNamespace}.Models
            {{
                public class {modelName}
                {{
                    { CreateModelPropertiesWithKeys(tableName) }
                }}
            }}";

            bool isSuccess = output
                             .RemoveIndents()
                             .WriteToFile($"{outputFolder}/{modelName}.cs", overwrite);

            return isSuccess;
		}


        // ===============================================================================
        // TECHNIQUE WITH PK Data Required - EXTRA SQL QUERIES
        // ===============================================================================

        private static string CreateModelPropertiesWithKeys(string tableName)
        {
            // REFERENCE: https ://docs.microsoft.com/en-us/dotnet/api/system.data.datatablereader.getschematable?redirectedfrom=MSDN&view=netframework-4.8

            var sb = new StringBuilder();
            var dataTable = new DataTable();


            using (var conn = new SqlConnection(sqlConnString))
            {
                conn.Open();

                var adapter = new SqlDataAdapter("SELECT * FROM " + tableName + " WHERE 0=1", conn)
                {
                    MissingSchemaAction = MissingSchemaAction.AddWithKey
                };
                adapter.FillSchema(dataTable, SchemaType.Mapped);
            };

            // loops through all the rows of the data table
            foreach (DataColumn col in dataTable.Columns)
            {
                bool isNullable = col.AllowDBNull;
                string dataTypeName = col.DataType.Name.DotNetTypeToCSharpType(isNullable);
                string columnName = col.ColumnName;

                string isKey = dataTable.PrimaryKey.Contains(col) ? $"{start}[Key]{end}" : "";
                bool hasMaxLength = (dataTypeName == "string" && col.MaxLength > 0 && col.MaxLength < 10000);
                string stringLength = hasMaxLength ? $"{start}[StringLength({col.MaxLength})]{end}" : "";

                sb.Append($"{isKey}");
                sb.Append($"{stringLength}");
                sb.AppendLine($"{start}public {dataTypeName} {columnName} {{ get; set; }}{end}");
            }

            var pkColumn = dataTable.Columns.Cast<DataColumn>().FirstOrDefault(f => dataTable.PrimaryKey.Contains(f)) ?? dataTable.Columns[0];

            sb.AppendLine($"{start}public override string ToString()");
            sb.AppendLine($"{start}{{");
            sb.AppendLine($"{start}\treturn $\"{ pkColumn.ColumnName}: {{{pkColumn.ColumnName}}}\";");
            sb.AppendLine($"{start}}}");

            return sb.ToString().RemoveStartEnd(start, end);
		}


        // ===============================================================================
        // ALTERNATE TECHNIQUE IF PK DATA NOT NEEDED
        // ===============================================================================

        private static string CreateModelProperties(string tableName)
        {
            var tableSchema = sqlTables.First(t => t.Key == tableName).ToList();
            var sb = new StringBuilder();

            foreach (var column in tableSchema)
            {
                bool isNullable = column.Is_Nullable.ToBool("YES");
                string dataType = column.Data_Type.TSqlTypeToCSharpType(isNullable);

                sb.AppendLine($"{start}public {dataType} {column.Column_Name} {{ get; set; }}");
            }
            return sb.ToString().RemoveStartEnd(start, end);
        }

    }
}
