<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Libs\**" />
    <EmbeddedResource Remove="Libs\**" />
    <None Remove="Libs\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CodingTests.cs" />
    <Compile Remove="Extensions\TestSteps.cs" />
    <Compile Remove="Extensions\TupleExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.4.0" />
    <PackageReference Include="AngleSharp.Css" Version="0.17.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildHare.Web\WildHare.Web.csproj" />
    <ProjectReference Include="..\WildHare\WildHare.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="C:\Users\Will Crowther\.nuget\packages\nunit3testadapter\3.10.0\build\netcoreapp1.0\Mono.Cecil.dll" Link="Mono.Cecil.dll" />
    <Content Update="C:\Users\Will Crowther\.nuget\packages\nunit3testadapter\3.10.0\build\netcoreapp1.0\nunit.engine.netstandard.dll" Link="nunit.engine.netstandard.dll" />
    <Content Update="C:\Users\Will Crowther\.nuget\packages\nunit3testadapter\3.10.0\build\netcoreapp1.0\NUnit3.TestAdapter.dll" Link="NUnit3.TestAdapter.dll" />
    <Content Update="C:\Users\Will Crowther\.nuget\packages\nunit3testadapter\3.10.0\build\netcoreapp1.0\NUnit3.TestAdapter.pdb" Link="NUnit3.TestAdapter.pdb" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData\WildHareTest.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
